### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/SSC-proposal#10]
Qu'est-ce qui nous coute de quoi pour le blog?

Traduction/révision à l'occasion (faudrait mettre un prix), mais dans le plus technique mettons...

**Comment by stecaron** [comment]
Y'a les frais pour le nom de domaine et certains gugusses de protection (environ 20-30$ par année).

**Comment by stecaron** [comment]
Pour le blog en tant que tel, en ce moment c'est sur que c'est pas des dépenses énormes. Beaucoup d'outils gratuits pareil.
