### ISSUE TITLE
Organizing events

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/SSC-proposal#11]
Ce sont quoi les dépenses qui s'en viennent? et quel montant on met en général pour l'organization d'événement?

Il y a du matériel pour filmer qui overlap avec le podcast déjà.

**Comment by stecaron** [comment]
Est-ce qu'on veut parler des verres réutilisables qu'on aimerait faire faire pour nos events? Si oui, peut-être un genre de 200-300$ pour une commande de verres qu'on distribueraient dans les événements.

**Comment by samperochkin** [comment]
Réutilisables dans le sens: on les ramasse à la fin?
