### ISSUE TITLE
Who we are

### ISSUE THREAD

**Issue by chblw** [dot-layer/SSC-proposal#12]
Pour l'instant, il nous manque qqch qui nous distingue des autres participants. Je crois qu'on devrais miser sur le fait qu'on es la relève : motivés, curieux et on veux partager. 

Le blog, le podcast, ML québec qui a commencé par un groupe FB, on devrait miser sur le fait qu'on es des jeunes (MP la plus vielle dans la demande je crois) qui utilisent des outils du 21e siecle pour partager notre amour des statistiques.

**Comment by samperochkin** [comment]
Je trouve pas que notre intro répond à cette critique encore, je vais essayer de quoi dans les prochains jours.
