### ISSUE TITLE
Quelle e-mail address?

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/SSC-proposal#2]
On utilise quelle e-mail pour le proposal?

 admin@dotlayer.org, communications@dotlayer.org ou info@dotlayer.org

**Comment by samperochkin** [comment]
comm I guess?

**Comment by stecaron** [comment]
Je dois retravailler sur 2-3 trucs pour l'adresse courriel demain. J'ai du revert des trucs hier a cause que le site était down. Je pense je sais qu'est qui ne marchait pas la .. 

Mais sinon ouais je prendrais communications@dotlayer.org I guess !

**Comment by davebulaval** [comment]
J'aime communications.
