### ISSUE TITLE
Meetup ML Quebec avant .Layer

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/SSC-proposal#3]
Hey pals. Quelqu'un peut me faire un mini résumé de ce qui a été fait avec Meetup avant les 3 derniers events de l'autre fois? Juste push un .txt dans le repo avec une petite liste ferait la job. Ou l'écrire ici si c'est mieux pour vous.

En passant, le dernier workshop et la conference etaient clairement des events Meetup, est-ce que le hackathon aussi était brandé "meetup"? L'essentiel c'est pas vraiment de savoir si c'était brandé Meetup, mais plutôt de savoir si c'est okay que je le passe comme ça dans le proposal.

**Comment by davebulaval** [comment]
Bonne question. Jpense qu'on va plus le brander .Layer à l'avenir (selon moi)

**Comment by stecaron** [comment]
Je m'occupe de la liste demain @samperochkin. 

Pour ce qui est du meetup de novembre, oui les 3 events étaient plus brandés "meetup", y  compris le hackathon. Je pense que dans le futur on veut toujours continuer à brander ça "Meetup". Genre continuer d'utiliser la page facebook Meetup. C'est juste que notre branding Meetup va utiliser en quelque sorte le branding de .Layer, dont les couleurs et tout. Dans les prochaines semaines, on pourra s'occuper de retaper les couleurs et le logo sur la page de Meetup pour ajouter les trucs à @jcyelle.

**Comment by stecaron** [comment]
@ngarneau est peut-être mieux placé que moi pour décrire ce qui a été fait avant le dernier meetup de novembre. Je pense que vous en avez fait un autre moins publicisé aussi hein @ngarneau ?  Mais sinon, de ma connaissance il y a eu:

- 4 novembre 2018: Meetup chez la compagnie Vooban. 3 talks d'environ 45 mins + séance de réseautage dans les bureaux de Vooban. Les talks touchaient les sujets des réseaux récurrents/LSTM, les GAN et l'utilisant du deep dans la robotique (Thales). Un peu plus de 40 personnes présentes.
- 10 mai 2018: Meetup chez la compagnie Coveo. 3 talks d'environ 45 mins + séance de réseautage dans les bureaux de Coveo. Les sujets des talks portaient sur YOLO (modèle de réconaissance d'objects en temps réel), Pytoune (une librairie similaire à Keras, mais pour Pytorch) et la recommandation adaptée au e-commerce (Coveo guys). Environ 30 personnes.
- 16 novembre 2017: Meetup à l'Université Laval. 3 talks d'environ 45 mins. Les sujets portaient sur l'initiation aux réseaux de neurones, les systèmes de recommandation et la classification de texte. De mémoire il y avait environ 30 personnes + un live streaming sur Facebook.

**Comment by ngarneau** [comment]
@stecaron il y en a eu un également le 23 novembre 2017 dans les bureaux d'XpertSea. Un talk d'environ 30-45 minutes avec réseautage. Le talk était principalement sur l'application du Deep Learning dans le domaine de l'aquaculture. Il y avait une trentaine de personnes.
