### ISSUE TITLE
Faire le lien entre les membres de .Layer et la SSC

### ISSUE THREAD

**Issue by chblw** [dot-layer/SSC-proposal#5]
Quelques points qu'on pourait soulever : 

1. 3 membres ont donné des talks au congrès annuel de la SSC 2017. 2 sont invited, dans la section ML en assurance. 
2. MP est sur le [comité des nouveaux chercheurs](https://ssc.ca/fr/comites/comite-nouveaux-chercheurs)  de la SSC.

**Comment by stecaron** [comment]
Très bon point @chblw  !

**Comment by samperochkin** [comment]
Excellent point je passais à côté. Prochaine fois j'ouvre le document, je travaille là-dessus. J'ai présenté (right??), tu as présenté, et MP à présenté. C'est ça?

**Comment by samperochkin** [comment]
Tu voulais dire 2018 aussi hein @chblw ?

**Comment by chblw** [comment]
Yes 2018 et c'est les bons noms @samperochkin
