### ISSUE TITLE
Occupations

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/SSC-proposal#7]
Si vous pouviez mettre vos titres / occupations dans le .tex ce serait nice.

Je vous conseille de ne pas compiler le document. Simplement de sauvegardé le .tex.

Direct dans le master si vous voulez.

**Comment by samperochkin** [comment]
Aussi, j'ai intégré les noms que j'avais besoin pour dire que nous sommes des membres de la ssc and so on et ceux que j'ai mis "en charge" de quelques choses. Est-ce que je devrais en ajouter. Je veux pas insulter personne non plus là y'a d'autres peeps qui pourrait être là.

**Comment by chblw** [comment]
Dans titre, propose tu de mettre nos titres (B.Sc / M.Sc / Ph.D / ACAS / AICA / FSA) sur la même ligne ?

P.ex. Samuel Perreault, M.Sc.

**Comment by samperochkin** [comment]
Intéressant. Allons-y comme ça. Je vais m'assurer que tout soit cohérent.

**Comment by chblw** [comment]
Je crois que JT pourrait être utile dans cette demande, même s'il n'est pas directement impliqué avec la SSC. Il sera probablement trésorier du RAMQ. Il nous aide aussi dans #12. FSA, M.Sc, CERA, chargé de cours, étudiant au doc et il apporte un mélange de pratique et recherche.
