### ISSUE TITLE
Community organization

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/SSC-proposal#8]
Qu'est-ce qui peux nous couter de quoi ou qui nous a couté de quoi?

Avec des prix en $$ ce serait mieux.

**Comment by davebulaval** [comment]
- Frais traduction
- frais encouru lors événements comme le 9 on paye un déjeuner 7,50$ par personne.
- Frais enregistrement OBNL 
- Logo et autres matériel de promotion. on achète un rool up c'est environ 130$

**Comment by stecaron** [comment]
Les frais d'enregistrement initial pour l'OSBL sont de 169$. Après ça, c'est 90$ par année je crois.
