### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/SSC-proposal#9]
Une description de ce que tu veux faire copy-paste ici? Je vais l'intégrer.

**Comment by samperochkin** [comment]
Aussi: les dépenses. Matériel pour filmer: combien de $$ ça?

**Comment by davebulaval** [comment]
[budget](https://www.dropbox.com/s/o51vk1yn78zev25/OpenLayerPrevisions_budgetaire.xls?dl=0)

Veut tu un autre format ?

**Comment by samperochkin** [comment]
@stecaron
